egonSchiele/contracts.ruby

lib/contracts.rb
lib/decorators.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

related to this comment https://github.com/egonSchiele/contracts.ruby/issues/51#issuecomment-68742587
@egonSchiele I have added a fix for deep contract violations when pattern matching. I was able to do that without changing public api (i.e. no additional `Match` keyword or anything like that).

Bug: Eliminates problems with pattern matching with deep contract violations

---

contracts.gemspec

It creates very weird history on rubygems if one forget to  update it when releasing new version, like this: https://rubygems.org/gems/contracts
```
0.5 - May 8, 2014 (24.5 KB)
```
even so, it was released recently.
Removing this field from gemspec allows rubygems to automatically set it to current day when releasing.

Remove explicit date from gemspec

---

Gemfile.lock
lib/contracts.rb
lib/contracts/decorators.rb
lib/contracts/errors.rb
lib/contracts/invariants.rb
spec/contracts_spec.rb

followup for #62 
issues descriptive error to not confuse users when they do:
```ruby
require 'contracts'
include Contracts
class X
class << self
Contract String => String
def hoge(name)
"super#{name}"
end
end
end
```
Previously this code failed somewhere with `undefined method on nil:NilClass`, which is totally sets user back wondering what could go wrong.
But now it fails rather nicely:
```
Contracts::ContractsNotIncluded: In order to use contracts in singleton class, please include Contracts module in original class
Example:
```ruby
class Example
include Contracts  # this line is required
class << self
end
end
```
... stacktrace ...
```

Followup/pull/62 :: Descriptive error when contracts are not included in owner class when used inside of singleton class

---

lib/contracts.rb
lib/contracts/decorators.rb
lib/contracts/method_reference.rb
lib/contracts/support.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

fixes #66 
As I thought, changing to aliasing instead of preserving method object, saves the day. Not only fixes the bug, but improves performance nicely:
master:
```
user     system      total        real
testing add                      0.460000   0.000000   0.460000 (  0.464251)
testing contracts add            4.380000   0.020000   4.400000 (  4.403810)
```
this branch:
```
user     system      total        real
testing add                      0.450000   0.010000   0.460000 (  0.448705)
testing contracts add            3.530000   0.010000   3.540000 (  3.542390)
```
@egonSchiele can you confirm performance improvement?

Bug/66: fix self in inherited singleton methods by changing original method preserving strategy

---

lib/contracts.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

fixes #72 
followup to #68 
Now it properly handles different combinations of presence of: splat in contract, proc/func/method in contract and block in arguments.
/cc @egonSchiele

fixes #72: a bit clever handling of splats and blocks combinations

---

TUTORIAL.md
lib/contracts/decorators.rb
lib/contracts/method_reference.rb
spec/contracts_spec.rb

Consider these definitions:
```ruby
klass = Class.new do
include Contracts
Contract String => nil
def process(laundry)
eat(laundry)
end
end
mod = Module.new do
include Contracts
include Contracts::Modules
Contract String => nil
def process(laundry)
eat(laundry)
end
end
```
They don't work as expected. In fact they fail with undefined method on nil exception. Because the assignment:
```
current = #{self}
ancestors = current.ancestors
```
becomes:
```
current = #<Class:004324234fc>
ancestors = current.ancestors
```
which is equal (since `#` starts one-line comment) to: `current = ancestors = current.ancestors`, in which case, yes, `current` is nil and we try to call `#ancestors` on it, which fails.
To avoid such problems with source-eval solution I have replaced it with ruby block solution, …

Allow contracts on anonymous classes and modules

---

lib/contracts.rb
lib/contracts/support.rb
spec/builtin_contracts_spec.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb
spec/module_spec.rb

fixes #77 
- Removes global inclusion of `Contracts` in `Object` from specs, so that there is no nasty bugs.

Bug/77 :: fix constant scoping issues

---

Gemfile.lock
lib/contracts/eigenclass.rb
lib/contracts/method_reference.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

Fixes #83 
During fixing this and while running a benchmark noticed that private methods defined in private section of class can't be defined because of an error, so as well added spec that exposes this and fixed it.
The fix to the original issue is as simple as including `Contracts` while `lift`ing eigenclass to contracted eigenclass.
Touched `Gemfile.lock` since it wasn't updated since last release.

Bug/83 :: Builtin contracts are not available on singleton classes

---

lib/contracts/decorators.rb
lib/contracts/eigenclass.rb

Addresses #96 - it defers to weird behavior in activesupport that appears to be on its way out, but activesupport is kind of a heavyweight to conflict with. Tests pass.

Singleton class visibility conflict

---

TUTORIAL.md

The tutorial recommended [the RDoc](http://www.rubydoc.info/gems/contracts/Contracts) if you want to see what each built-in does, but that has the following problems:
- the contracts are mixed in with irrelevant classes like `ContractsNotIncluded` and `MethodDecorators`
- the contracts are sorted alphabetically, instead of grouping related contracts together
- each contract must be clicked on to see each description – there is no one page that shows an overview of all built-in contracts
So I wrote summaries in the tutorial, with links to the RDoc for each class.
I also changed “builtin” to “built-in”. It looks more grammatical to me.

In the tutorial, summarize what each built-in does

---

lib/contracts/builtin_contracts.rb

You can currently see the problem at http://www.rubydoc.info/gems/contracts/Contracts.

Fix indentation in Contracts module documentation

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

Sometimes I'd like to test an argument is equal to a defined set of values. This currently works when I'm dealing with most values, but not when my values are classes.
```ruby
class Foo
end
Contract Foo => Any
def foo(arg)
end
foo(Foo.new)  # Works.
foo(Foo)  # Contract error.
```
This adds support for an `Eq` contract, which allows for equality comparison of classes (or anything) using `.equal?`.
```ruby
class Foo
end
Contract Eq[Foo] => Any
def foo(arg)
end
foo(Foo.new)  # Contract error.
foo(Foo)  # Works.
```

Add `Eq` Class for contracts around equality.

---

TUTORIAL.md
lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

Should really have a `Nat` contract, and should make it 100% clear that `Pos` and `Neg` do not include 0.

Add `Nat` Contract

---

lib/contracts.rb
lib/contracts/formatters.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

Fixes #108. `to_s` is now called on contracts within Hashes and Arrays.
to_s is recursively called on Hashes and Arrays, so even nested Hashes or Arrays will contain pretty contract representations.
Contracts module prefix is now removed from classes, this makes more sense to me as when you write a contract such as `Contract Num => nil` you'd expect the error to be `Expected: Num` rather than `Expected: Contracts::Num`.
Custom to_s messages will be wrapped in round brackets to differentiate from standard Strings. E.g. `Expected: (a number)`. Without this custom messages get confusing in nested hashes or arrays. Alternatives might be angle brackets (but these get confused with hash rocket syntax) or backticks.
Primitive values e.g. 42, true, nil will be left alone, no erroneous conversion …

Improve to_s formatting in error's Expected field.

---

lib/contracts.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb
spec/ruby_version_specific/contracts_spec_1.9.rb
spec/ruby_version_specific/contracts_spec_2.0.rb
spec/ruby_version_specific/contracts_spec_2.1.rb
spec/spec_helper.rb
spec/support.rb

Complex method signatures that Ruby allows should now work with Contracts, which fixes #100. Pattern matching with differing arities now works too, which fixes #90. Also fixed some tests that didn't test what they meant to, and added separate test files for syntax only supported by newer Rubies.
Before, Contracts made some assumptions about method signatures that were stricter than what Ruby allows. This meant that many methods could not be annotated with Contracts. The problem was assuming that a splat always comes last, when it need not.
I fixed this by looping forwards validating the args up to the splat (or to the end if there isn't one), then looping backwards validating to the splat, then fixing the validator to the splat one and validating any remaining args with that.
This worked, …

Improved arg validation parsing.

---

lib/contracts/formatters.rb

YARD documentation generation for Contracts has been made a gem [yard-contracts](https://github.com/sfcgeorge/yard-contracts) Fixes #32 
This pull request adds a minor feature to the Formatters. The new `full` parameter means inspect will output an empty string (when `full=false`) if the `to_s` value would be useless. This is to prevent duplication in yard-contracts; A param docstring is the type (inspect) followed by the description (to_s). Without this patch the type and description can end up being the same which looks odd.
In MRI Ruby < 2 inspect calls to_s so they _always_ are the same. I couldn't find a way to make this work in those old Rubies. JRuby 1.9mode is fine. It doesn't affect the main Contracts gem because when they are the same it calls inspect, but as inspect calls to_s …

Add initial YARD support

---

lib/contracts/builtin_contracts.rb
lib/contracts/formatters.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

`useful_to_s?` wasn't useful on Ruby < 2.0 as `#inspect` simply called `#to_s` so they were always the same. I've fixed that so it works properly in all Rubies.

Fix useful_to_s? on older Rubies < 2.0

---

TUTORIAL.md
lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

Adds ability to use `HashOf` in this manner:
```ruby
Contract HashOf[KeyContract => ValueContract] => ...
```
WDYT?
btw, old syntax is still preserved, ie: `HashOf[KeyContract, ValueContract]`

Make HashOf contract prettier

---

lib/contracts.rb
lib/contracts/decorators.rb
spec/fixtures/fixtures.rb

In many languages, a type signature for a function that increments a number by one looks like `Num -> Num`, which is represented fine in this library as `Contract Num => Num`. But for a function that just returns a value, say pi: What is pi? Pi is a Num (or Float/BigDecimal/whatever). Pi is not a `nil => Num`. I think it would improve the readability of the contract type signatures if there was a way to express the type of a declared value or computed value as a single type, and omit the `nil =>`.
This change allows you to write:
```rb
Contract Num
def pi
3.14
end
```

Change syntax for no arguments

---

lib/contracts.rb
lib/contracts/builtin_contracts.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

Fix maybe proc

---

lib/contracts.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

honor Func contract on returns (fixes issue #143)

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb

Pos and Neg contracts explode when passed nil values. This is most easily noticed when combined with Maybe -  `Maybe[Pos]` - which will error when a positive value is not provided.
For example:
```
1) Contracts: Pos: should fail for nil
Failure/Error: expect { @o.pos_test(nil) }.to raise_error(ContractError)
expected ContractError, got #<NoMethodError: undefined method `>' for nil:NilClass>
```

Fix Pos,Neg contracts which fail incorrectly for nil values

---

TUTORIAL.md
lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb
spec/ruby_version_specific/contracts_spec_2.1.rb

Fixes #131 
Allows to do this:
```ruby
Contract OptHash[nfiles: Opt[Nat], mfiles: Nat] => ArrayOf[String]
def list(nfiles: 10, mfiles:)
[]
end
list(nfiles: 4, mfiles: 77)
list(mfiles: 77)
list(mfiles: 77, nfiles: nil)
```
Contract names are subject to discussion.

Add KeywordArgs and Optional contracts

---

TUTORIAL.md
lib/contracts.rb
lib/contracts/call_with.rb
lib/contracts/support.rb
lib/contracts/validators.rb
spec/override_validators_spec.rb

- Extracted `#call_with` to its own module, without any changes to it.
- Extracted + Refactored `.make_validator` in its own module.
- Add ability to override validator strategies and add new ones (sort of, for user custom contracts)
- Make all calls to `Contract.make_validator` faster by memoizing
fixes #150 
fixes #156 
Example code for overriding `:class` strategy:
```ruby
require "rspec"
require "contracts"
Contract.override_validator(:class) do |contract|
lambda do |arg|
arg.is_a?(contract) || arg.is_a?(RSpec::Mocks::Double)
end
end
```
@robnormal What do you think, can you use this kind of overriding mechanism?
/cc @egonSchiele Can you take a look at this one?

Refactor validator strategies + Add ability to override validators

---

spec/override_validators_spec.rb

Recent rspec release changed how double's inspect behaves slightly. So we need to adjust this one spec.

[rspec update] Fix rspec double related spec

---

TUTORIAL.md
lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

E.g. RangeOf[Nat] or RangeOf[String] or ...
Includes tests but not TUTORIAL.md as that is under potential change
from pull request #170.
[Feature request #169]

RangeOf[...] implemented

---

TUTORIAL.md

There are three commits in this pull request. One to add Eq and Func. One to arrange the list into groups. One to make a few changes to wording and examples.
This addresses the documentation deficiency identified in #168.

Update tutorial builtin contract list

---

.travis.yml

Workaround for travis ruby 2.1 built-in bundler of being too old.
reference: https://github.com/travis-ci/travis-ci/issues/3531

Update bundler before doing bundle install

---

TUTORIAL.md
lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

I use contracts.ruby within a configuration class. Some [options](https://github.com/cucumber/aruba/blob/master/lib/aruba/config.rb#L38) only allows a given subset of values - symbols. I added a custom contract for that, but thought it might be valueable for others as well.

Added enum contract

---

TUTORIAL.md
lib/contracts/validators.rb
spec/fixtures/fixtures.rb
spec/validators_spec.rb

fixes #167 
Implemented first option:
```ruby
Contract (1..10) => String
def do_something(range)
```

Add Range validator

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb
spec/ruby_version_specific/contracts_spec_2.1.rb

Wasn't sure where to put the KeywordArgs specs - let me know if it should go in spec/contracts_spec.rb or whatnot (or if I'm otherwise way off base)

Make KeywordArgs fail if unexpected keys are passed in

---

lib/contracts.rb
lib/contracts/call_with.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb

When varargs are given with a maybe[block], and the block is not provided, do not append an extra nil to the varargs (see waterlink's issue #161).
What do you think of this @waterlink ?

bug fix for varargs with a maybe[block]

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

Given these HashOf contracts:
```ruby
Contract HashOf[Symbol => String] => Any
def foo(args)
end
Contract KeywordArgs[:hash => HashOf[Symbol => String]] => Any
def bar(args)
end
```
calling `foo(nil)` or `bar(hash: nil)` results in `NoMethodError: undefined method ``keys' for nil:NilClass`

Do not allow non-hash values in HashOf contract

---

TUTORIAL.md
lib/contracts.rb
lib/contracts/core.rb
spec/builtin_contracts_spec.rb
spec/contracts_spec.rb
spec/fixtures/fixtures.rb
spec/module_spec.rb
spec/override_validators_spec.rb
spec/ruby_version_specific/contracts_spec_1.9.rb
spec/ruby_version_specific/contracts_spec_2.0.rb
spec/ruby_version_specific/contracts_spec_2.1.rb

This is a first stab on #157.
This refactoring does:
- Extracts `Contracts::Core` out of `Contracts`;
- Makes `include Contracts` include `Contracts::Core` for backwards compatibility;
- Factors out specs to use `Contracts::Core`;
- Makes `TUTORIAL.md` use `Contracts::Core` use it by default to encourage new users of contracts to use `include Contracts::Core` right away;
- Mentions shortcut `C = Contracts` in `TUTORIAL.md`.
/cc @egonSchiele @sfcgeorge @nixpulvis @robnormal

Refactor :: Extract contracts core

---

TUTORIAL.md
lib/contracts/validators.rb
spec/fixtures/fixtures.rb
spec/validators_spec.rb

For a recent project this contract would have been handy:
```ruby
RGB = Match[/\#h{6}/] # e.g. '#ffffff'
Contract RGB => nil
def assign_color(color)
end
```
Other example:
```ruby
Contract Match[default_mail_regexp] => nil
def send_invitation(email)
...
```
As it's not easy to get the effect of a logical AND with regular expressions, so I added that as well:
```ruby
PartnerEmail = Match[default_mail_regexp, /(company1|company2)\.com\z/]
Contract PartnerEmail => nil
def invite_to_project(email)
```
Hopefully it's useful to others! If so I'm happy to move the explanation to the tutorial.

Add match-contract

---

lib/contracts/core.rb
spec/contracts_spec.rb

Fixes #176 
Our current routine while including or extending `Contracts` is to define `Contract(*args)` method for current class and make it just delegate to `self.class.Contract`. But in case of:
```ruby
m = Module.new do
include Contracts::Core
end
Class.new do
include Contracts::Core
extend m
Contract String => nil
def foo(x)
end
end
```
it doesn't work, since there is no `self.class.Contract` at this point of time. But, there is just `Contract` already in super class, and we may just call it. That is what this PR does: verifies if there is a `Contract` method in super class and calls it instead of delegating to `self.class.Contract`.
/cc @PikachuEXE @egonSchiele

Fix classes that extend modules where contracts were included

---

TUTORIAL.md
features/builtin_contracts/int.feature
features/builtin_contracts/nat_pos.feature
lib/contracts/builtin_contracts.rb

Fixes #204 by adding builtin `Int` and `NatPos` contracts.
Added to TUTORIAL.md and fixed documentation links by namespacing builtin.
Added to cucumber features and tested still passing.

Number fields

---

CHANGELOG.markdown
lib/contracts/version.rb

Closes #220 
This PR:
- Updates changelog with latest changes.
- Bumps up version to `v0.13.0`
/cc @egonSchiele Can you take a look?

Release v0.13.0

---

README.md

Reason for change:
* The `README.md` was reading a bit weird without the syntax highlighting.
Change:
* Wrap the example error message in triple backticks.

Add syntax highlighting for error message

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

This adds the ability to make assertions on the class hierarchy of a class being passed as an argument. It should be useful when using things like the Adapter Pattern or Dependency Injection.
Consider the following example:
```ruby
class SlackClientAdapter < BaseClient
end
class HipchatClientAdapter < BaseClient
end
Contract C::DescendantOf[BaseClient] => BaseClient
def start_client(client_class)
@client = client_class.new
end
start_client(SlackClientAdapter)
start_client(HipchatClientAdapter)
```
This is a demonstration of what I'm actually doing on a real app (although the example itself is totally made up).
I want to be able to assert that the argument is not just a class, but a descendant of `BaseClient` (this base client serves as an abstract class this example. God, I feel like a …

Adds DescendantOf

---

Gemfile

The gemfile was limiting rubocop to only [2.0..2.2], so `rake` would
fail for me on 2.3

Adds rubocop in ruby 2.3

---

LICENSE
contracts.gemspec

Currently the project license is not specified in the gemspec or in a LICENSE file. The README states that the project is BSD licensed, without specifics. Adding this specification allows tools such as  [LicenseFinder](https://github.com/pivotal/LicenseFinder) to identify the license automatically.
I had to guess on the specific BSD license desired, I went with the Simplified BSD as a start.

Specify license

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

This leads to issues when methods are overloaded, because when the
KeywordArgs gets checked on a non-hash argument, it raises an exception
rather than failing properly.

Fixed issue where KeywordArgs is not checked if it is a hash.

---

TUTORIAL.md
lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb
spec/fixtures/fixtures.rb

Adds a StrictHash builtin contract, which checks that the argument is
a hash, and every key passed is present in the given contract.
https://github.com/egonSchiele/contracts.ruby/issues/235

StrictHash

---

lib/contracts/decorators.rb

ActiveRecord::Base.inherited needs to be called in order for models to be setup correctly.
Fixes #223

Fix contracts used in AR-models

---

spec/builtin_contracts_spec.rb

problem: 
- specs are a bit hard to read
solution: 
- use `fails` / `passes` methods to indicate desired expectation 
- specs become more declarative and descriptive
- the changes are of mechanical nature, no new logic is introduced

make specs less noisy to read by using declarative expectations

---

Gemfile
lib/contracts/call_with.rb
spec/methods_spec.rb

This commit fixes issue with contracts for function that takes blocks. Return type is now enforced properly for blocks.

fixes issue #242 - contract's return value is now enforced with blocks properly

---

README.md

`rake spec` don't run required `ruby_version_specific` spec, therefore command actually running that is `rspec`.

add to readme.md info about running `rspec`

---

.travis.yml
CHANGELOG.markdown
README.md
Rakefile
lib/contracts/support.rb

As per the conversation in:
https://github.com/egonSchiele/contracts.ruby/pull/255

Drop support for Ruby 1.8.

---

lib/contracts/builtin_contracts.rb
spec/builtin_contracts_spec.rb

`Contracts::StrictHash` didn't complain about extra entries in a given
hash. This was because of the missing assertion for keys. Specs hadn't
caught this case because `age` key had a wrong type anyway.
Compare keys for contract and a given hash and return false if they are
equal.

Fix StrictHash contract for extra keys

---

TUTORIAL.md
lib/contracts.rb
lib/contracts/attrs.rb
spec/attrs_spec.rb

This pull request adds a new module `Contracts::Attrs` containing three methods to assist in using contracts with object attributes:
- `attr_reader_with_contract <symbol>..., <contract>`
- Wraps `attr_reader`, validates contract upon 'getting'
- `attr_writer_with_contract <symbol>..., <contract>`
- Wraps `attr_writer`, validates contract upon 'setting'
- `attr_accessor_with_contract <symbol>..., <contract>`
- Wraps `attr_accessor`, validates contract upon 'getting' or 'setting'

Add a `Contracts::Attrs` module containing attribute w/ contracts utilities.

---

.travis.yml

[1.9.2 now fails to build on Travis using `precise`](https://github.com/travis-ci/travis-ci/issues/7743), but we can use Trusty now :)

Upgrade ruby-1.9.2 dist to trusty

---

lib/contracts/attrs.rb
spec/attrs_spec.rb

:wave:
When passing in multiple fields to a single attr_x_with_contract call, the current implementation only applies the contract for the first field.
```ruby
class Thinger
include Contracts
include Contracts::Attrs
attr_accessor_with_contract :a, :b, :c, String
end
```
```
[development] » t = Thinger.new
» #<Test:0x007f934f552dc0>
[development] » t.c
» nil
[development] » t.b
» nil
[development] » t.a
ReturnContractError: Contract violation for return value:
Expected: String,
Actual: nil
Value guarded in: Test::a
```
This applies the contract and attr_reader individually to each field.

Apply contracts to each name for multi-attribute calls

---

Gemfile

This PR avoids the http endpoint, using the HTTPS one.

Gemfile: use https RubyGems source

---

CHANGELOG.markdown

This PR edits the change log document to 
- add **GitHub compare links** to show what changed since last release
- add **relase dates** for each release
These changes were inspired by the [Keep A Changelog 1.0.0](http://keepachangelog.com/en/1.0.0/) initiative.
---
A question for the reviewer:
- Do you think it would make the document _better_ if the links for titles such as `v0.11.0` were collected at the end of the whole document, or is it fine like it is now (links interspersed after each title)

CHANGELOG: add GitHub compare links, release dates

---

lib/contracts/call_with.rb
spec/ruby_version_specific/contracts_spec_2.1.rb

This tiny PR fixes all (2) misspellings found by running the following command on the codebase:
```
find . | misspellings -f -
```
[misspellings](https://pypi.python.org/pypi/misspellings) is a Python program which:
> check[s] for misspelled words in source code. It does this by looking for words from a list of common misspellings. The dictionary it uses to do this is based on the Wikipedia list of common misspellings.

Fix two tiny misspellings in comments

---

lib/contracts/method_handler.rb

AFAICT, `name` is not defined at that point

Fix typo in Contracts::MethodHandler#validate_decorators!

---

lib/contracts/call_with.rb
lib/contracts/method_handler.rb

Using exceptions for control flow is slower than using conventional control flow in all implementations of Ruby I tried, and has particularly bad performance on optimising implementations of Ruby. This PR makes each test on a failing method overload 3x faster in MRI, and allows optimising implementations of Ruby like JRuby and TruffleRuby run it up to 10x faster than that.
https://github.com/graalvm/truffleruby/issues/697

Don't use exceptions for control flow

---

.travis.yml

Two (related) changes:
* Test on Ruby 2.5.
* Don’t specify tiny version (e.g. specify `2.4`, not `2.4.2`). This avoids having to manually update `.travis.yml` when a newer tiny version is released.

Test on all the latest Rubies

---

lib/contracts/call_with.rb

See https://github.com/egonSchiele/contracts.ruby/issues/278#issuecomment-351428779 and https://github.com/egonSchiele/contracts.ruby/pull/281#issuecomment-362851436
Somehow Travis CI didn't like that I reasigned the blk variable. So I introduced a new target_blk variable.

Wrapping &blocks only when there is a Func check. (second version) (bug 278)

---

.github/workflows/code_style_checks.yaml
.github/workflows/tests.yaml
.gitignore

https://www.reddit.com/r/ruby/comments/jt2uub/deep_dive_moving_ruby_projects_from_travis_to/
Travis will no longer be free for Open Source projects (And it's already slow for OS projects now)
This is to move to GitHub Action for CI
Same Ruby versions plus 2.6-2.7
JRuby still used for code style checks but different version due to what [`ruby/setup-ruby` action](https://github.com/ruby/setup-ruby) supports
Old Ruby versions might fail

Create GitHub Workflow config to simulate Travis builds

---

.github/workflows/tests.yaml

This PR just adds Ruby 3.1 to the CI matrix.
As a side note, there's an `include` in the config that I don't think is necessary.  The specs run twice for Ruby 3.0 - once with both rspec and cucumber, and then one with rspec only.  The latter is the result of the include, which I believe can be removed.

Add Ruby 3.1 to the CI matrix

---

contracts.gemspec
lib/contracts.rb

Two minor improvements:
1. Automatically load `version.rb`, so that `Contracts::VERSION` is always accessible to user
2. Hide the gem deprecation warning if the user is already on the latest version

Always load version.rb, suppress legacy deprecation warning

---

features/builtin_contracts/keyword_args_with_optional_positional_args.feature
lib/contracts.rb
lib/contracts/call_with.rb

Fixes https://github.com/egonSchiele/contracts.ruby/issues/304

Fix keyword arguments contract when used with optional positional arguments

---

features/advanced/pattern_matching.feature
lib/contracts/method_handler.rb

Fixes https://github.com/egonSchiele/contracts.ruby/issues/307

Fix pattern matching
