egonSchiele/contracts.ruby

- TUTORIAL.md
> Fix a typo in TUTORIAL.md

- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
Explanation here: https://github.com/waterlink/contracts.ruby/commit/0f8287dc31af81ee067f573e5529d9b3ac0dedd6#commitcomment-9225203
> Cover deep contract violation during pattern matching better

- lib/contracts.rb
- lib/contracts/decorators.rb
- spec/contracts_spec.rb
- spec/spec_helper.rb
> Fix/31 :: Allow overriding of failure callback while using pattern matching

- lib/contracts.rb
- lib/contracts/core_ext.rb
- lib/contracts/decorators.rb
- lib/contracts/eigenclass.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
> Bug/37 :: Allow usage of singleton classes

- lib/contracts.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
> Bug/65: Args splat with block argument at the end

- TUTORIAL.md
- lib/contracts.rb
- lib/contracts/decorators.rb
- lib/contracts/eigenclass.rb
- lib/contracts/modules.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
> Bug/44: Fix contracts on modules

- lib/contracts/version.rb
@egonSchiele since #77 was pretty severe bug, can you please release 0.6?
> Bump up version 0.6

- Gemfile.lock
- lib/contracts/decorators.rb
- lib/contracts/method_reference.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
> Handle protected methods correctly

- README.md
Just a tiny Readme update. Badges are sexier now, and I added a few words and a link to wikipedia.
> Badge changes and a few lines about contracts.

- TUTORIAL.md
- lib/contracts/builtin_contracts.rb
- spec/builtin_contracts_spec.rb
- spec/fixtures/fixtures.rb
To me this contract looks generic enough to be included as builtin contract. What do you think?
> Add SetOf builtin contract

- CHANGELOG.markdown
Can't read well currently (unless in raw data form)
> Update CHANGELOG to be easier to read

- lib/contracts.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
> Recognize module as a class contract

- lib/contracts/builtin_contracts.rb
- spec/builtin_contracts_spec.rb
This bug was in Nat. Also fixed equivalent bugs in Pos and Neg.
Also beefed up a few tests for Pos, Neg, Nat.
> Fixed #165: "Bug: comparison of Symbol with 0 failed"

- TUTORIAL.md
A brief section near the end to describe the use of `Contract.valid?`.
Also fixed a single typo (separate commit).
Aside: I think the comment for `Contract.valid?` is out of date. It says it returns a tuple but I think it just returns true/false.
> Tutorial: new section "Using contracts within your own code"

- CHANGELOG.markdown
So this is the list of important changes between `0.9` and `0.10`. My wording is probably not the best, so please review :)
/cc @egonSchiele @PikachuEXE
> Update changelog for 0.10

- README.md
- TUTORIAL.md
Does exactly what the title says ;)
/cc @egonSchiele @PikachuEXE 
fixes #200
> Add note on 'include Contracts::Builtin' to tutorial

- CHANGELOG.markdown
- lib/contracts/version.rb
I think we might want to release that, it has useful additions and important-ish bug fix.
/cc @egonSchiele
> Changelog and bump for v0.12.0

- lib/contracts/decorators.rb
- lib/contracts/engine/eigenclass.rb
- lib/contracts/engine/target.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
- spec/override_validators_spec.rb
- spec/validators_spec.rb
> Allow contracts on singleton class of subclass

- features/builtin_contracts/args.feature
Rendered staging doc can be seen here: https://www.relishapp.com/contracts-staging/contracts-ruby/docs/builtin-contracts/args
> Add docs for builtin Args contract

- lib/contracts/core.rb
- spec/contracts_spec.rb
- spec/fixtures/fixtures.rb
Based on my comment in issue #229
> issue #229: fix constant lookup when including a module that already includes Contracts

- README.md
Changing the documentation since we now test for Ruby versions 2.3, 2.4 and 2.5.
> Update README.md to reflect new ruby versions.

- contracts.gemspec
This is to comply with the plan raised at
https://github.com/egonSchiele/contracts.ruby/issues/294#issuecomment-768844784
Opening this PR for discussion
> * Update gemspec post install message to notify about gem's future plan
